#include "Main.hpp"

// Raw unique identifier
unsigned char RawUUID[] = {
	0x3A,0x0B,0x10,0x1F,0x49,0xA4,0x42,0x0F,0x9A,0x0B,0x95,0xA8,0xC8,0x86,0x51,0x1A
};

static btstack_packet_callback_registration_t HCIEventRegist;
static btstack_packet_callback_registration_t L2CAPEventRegist;
static btstack_packet_callback_registration_t SMEventRegist;

static unsigned char BatteryLvl = 100;

void MainSetup(){
	// CYW43 driver architecture
	if (cyw43_arch_init()){
		COut("CYW43_arch failed to initialize");
	}

	// l2cap
	l2cap_init();

	// SM Display only
	sm_init();
	sm_set_io_capabilities(IO_CAPABILITY_NO_INPUT_NO_OUTPUT);
	sm_set_authentication_requirements(SM_AUTHREQ_SECURE_CONNECTION | SM_AUTHREQ_BONDING);

	// ATT
	// Profile data generated by CMake
	att_server_init(profile_data, NULL, NULL);

	// Batt service
	battery_service_server_init(BatteryLvl);

	// HID service
	hids_device_init(0,HIDDescriptorKbdBootMode, sizeof(HIDDescriptorKbdBootMode));

	// Advertisements
	unsigned short AdvMin = 0x0030;
	unsigned short AdvMax = 0x0030;
	unsigned char AdvType = 0;
	bd_addr_t BleAddr;
	memset(BleAddr, 0, 6);

	gap_advertisements_set_params(AdvMin, AdvMax, AdvType, 0, BleAddr, 0x07, 0x00);
	gap_advertisements_set_data(AdvDataLen, (unsigned char*) AdvData);
	gap_advertisements_enable(1);

	// Event registry
	HCIEventRegist.callback = &PawketHandler;
	hci_add_event_handler(&HCIEventRegist);

	// Conn param update registry
	L2CAPEventRegist.callback = &PawketHandler;
	l2cap_add_event_handler(&L2CAPEventRegist);

	SMEventRegist.callback = &PawketHandler;
	sm_add_event_handler(&SMEventRegist);

	COut("Main setup finished!");
}

static void PawketHandler(unsigned char PawketType, unsigned short Channel, unsigned char* Pawket, unsigned short Size){

}

int main(void){
	COut("Initializing starry keyboard");
	return 0;
};